### ISSUE TITLE
Load key invalid format

### ISSUE THREAD

**Issue by rpgwaiter** [LuisEnMarroquin/setup-ssh-action#1]
```
debug1: Trying private key: /home/runner/.ssh/access
Load key "/home/runner/.ssh/access": invalid format

```
I'm not sure what I could be doing wrong. I generated a fresh rsa key, copy/pasted it into github secrets, ensured I could use it locally for ssh to my server. Still get this error with the actions. Any idea what could cause that?

**Comment by LuisEnMarroquin** [comment]
Hi @rpgwaiter did you figured out what was wrong?

**Comment by rpgwaiter** [comment]
Yeah, my key wasn't in PEM format 🥳
